/* ============================================================================
   World mask — a 192x96 land/ocean bitmap in equirectangular lat/lon.

   Derived from the brand plate (public/images/world-network.png) by inverting
   its Mercator projection and thresholding luminance, so the continents the
   hero globe draws are the same ones the mark is built on. 2.3kb packed, one
   bit per cell, decoded once on first use.

   Regenerated only if the brand plate changes; the source projection is
   Mercator cropped to roughly +78..-56 latitude, which is why the poles read
   as ocean here — no dot is ever placed on them.
   ========================================================================== */

export const MASK_W = 192;
export const MASK_H = 96;

const PACKED =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////4AAAAAAAAAAAAAAA" +
  "AAAAAAAAAA//////8AAAAAAAAAAAAAAAAAAAAAAAAAB/////MAAAAAAAAAAAAAAAAAAAAAAA8AAL" +
  "////7AAAAAAAAAAAAAAAAAAB/////gD/////AAYAAAAAAAAAAAAAAAaI+Af/+D//////4AP+AAAA" +
  "AAAAAAAAAN+E/wH///gA/////////4MAAAAAAAH9w///YeH+f/gB/////v///////4AAAA/8Hf/+" +
  "wcH/+AP//////////////4AAAP//+f/wDwQf/5//////////////rwAAAHwA+P/8D+DwAP//////" +
  "///////AGAAAAOAAPj//n/sAAf////////////+AOB4AAAAAH/////8AAB/////////////4EAAA" +
  "AAAAH//9/84CAB/////////////8AAAAAAAAf////+AYAD/////z///////0AAAAAAAAf////8AA" +
  "AA////Dz///////jwAAAAAAA/////8AAAA/////5///////vwAAAAAAAf////w8AAA//+//5////" +
  "////wAAAAAAAH///+BAAAAP/4P//////////4AAAAAAAB///8AAAAAf/5///////////4AAAAAAA" +
  "AP//8AAAAAf/////////////AAAAAAAAAX/D4AAAgB/////////////wAAAAAAAAAb+A8AAAcH/7" +
  "//v////////gAAAAAAAAAH/D/gAAPv////3/g/////8AAAAAAAAAAD+Y/8AH//////z/5/////4A" +
  "AAAAAAAAAA/wH8AAf//87/7/z//3//4AAAAAAAAAAAH8D+AAH/////5/z//D//4AAAAAAAAAAAB8" +
  "D6AAD/////8+HP/D/4wAAAAAAAAAAAAeP+AAD/////+wEH+B/g4AAAAAAAAAAAAP//AAP////9/A" +
  "IH/B/g+AAAAAAAAAAAAA//AA+H//+Dv8QH/A/AeAAAAAAAAAAAAAf/4AAD///wf8gP/D/AfAAAAA" +
  "AAAAAAAB//8AABgH/h/5B//j+B+AAAAAAAAAAAAH///gAAAD/j/z+A/n+DBAAAAAAAAAAAAH///g" +
  "AAAB/h/3gAAH//AgAAAAAAAAAAAD/5/wAAAH//f8AAAD//hwAwAAAAAAAAAD/9//AAAD/+e8AAAB" +
  "//AQAAAAAAAAAAAB////gAAD///wAAAA/+QLgAAAAAAAAAAB/7n/wAAB//9gAAAAP8YD8AAAAAAA" +
  "AAAB/4B/gAAAf/9AAAAAH+AB+AAAAAAAAAAA/9H/gAAAf/+AAAAAD+AB+AADAAAAAAAAf//+AAAA" +
  "f/8AAAAAAH8AAAAAAAAAAAAAf//+AAAAf/8EAAAAAAAYQAAAAAAAAAAAD//8AAAA//8EAAAAAAAc" +
  "QAAAAAAAAAAAB//+AAAA//8cAAAAAAD8YAAAAAcAAAAAB//+AAAAf/44AAAAAAP/cAAAAAMAAAAA" +
  "B//8AAAAf/wYAAAAAAP//AAAAAAAAAAAB//8AAAAP/g4DgAAAA///gAAAAAAAAAAB//4AAAAP/ww" +
  "DgAAAH///wAAAAAAAAAAD/+AAAAAP/gwAAAAAH///8AAAAAAAAAAH/8AAAAAP/gAAAAAAP///8AA" +
  "AAAAAAAAH/4AAAAAP/gAAAAAAH///4AAAAAAAAAAP/wAAAAAf+AAAAAAAH///wAAAAAAAAAAP/AA" +
  "AAAAf/AAAAAAAH///wAAAAAAAAAAH+AAAAAAf8AAAAAAAHwP/wAAAAAAAAAAH4AAAAAAPwAAAAAA" +
  "AAAD/gAAAAAAAAAAHwAAAAAAAAAAAAAAAAAB+AHgAAAAAAAAHgAAAAAAAAAAAAAAAAAAeADAAAAA" +
  "AAAAPAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAPgAAAAAAAAAAAAAAAAAAQAIAAAAAAAAAHAAAAAAA" +
  "AAAAAAAAAAAAAAwAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

let bits: Uint8Array | null = null;

function decode() {
  const binary = atob(PACKED);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

/** True where the given point (degrees) falls on land. */
export function isLand(latDeg: number, lonDeg: number) {
  if (!bits) bits = decode();
  let col = Math.floor(((lonDeg + 180) / 360) * MASK_W);
  let row = Math.floor(((90 - latDeg) / 180) * MASK_H);
  if (col < 0) col += MASK_W;
  if (col >= MASK_W) col -= MASK_W;
  if (row < 0) row = 0;
  if (row >= MASK_H) row = MASK_H - 1;
  const index = row * MASK_W + col;
  return (bits[index >> 3] & (128 >> (index & 7))) !== 0;
}
